In [369]:
import pandas as pd
import numpy as np
import os
import matplotlib as plt

In [748]:
markers_df = pd.read_csv("lifu_markers_1_2back_test.csv")
# calibration_complete =markers_df[markers_df["marker"] == "START_EXPERIMENT_RECEIVED"].iloc[-1]
# calibration_complete = calibration_complete["LSL_timestamp"]
markers_df_on = markers_df[markers_df["marker"] =="LIFU_ON"]
markers_df

,Time,marker,LSL_timestamp
0,3.236809,collecting_baseline,1.693274e+06
1,3.258948,collecting_baseline,1.693274e+06
2,3.309343,collecting_baseline,1.693274e+06
3,3.337800,collecting_baseline,1.693274e+06
4,3.393953,collecting_baseline,1.693274e+06
...,...,...,...
207,48.304111,LIFU_ON,1.693319e+06
208,53.629745,LIFU_OFF,1.693325e+06
209,55.592549,LIFU_ON,1.693326e+06
210,60.915801,LIFU_OFF,1.693332e+06


In [749]:
eeg_df = pd.read_csv("eeg_LSL_gpype2back_test.csv")#("thetaEEG_gpype_2back_-1580742246_20260702_093834.csv")
eeg_df

,Time,Ch01,Ch02,Ch03,Ch04,Ch05,Ch06,Ch07,Ch08,Ch09,Ch10,Ch11,Ch12,Ch13
0,1.693272e+06,199999.968750,199999.96875,199999.96875,199999.96875,73926.976562,199999.968750,199999.96875,1097.605103,1.204737e+06,4.072512e+08,9.742852e+07,1.017940e+08,17.890985
1,1.693272e+06,199999.968750,199999.96875,199999.96875,199999.96875,74181.585938,199999.968750,199999.96875,1958.274780,3.834840e+06,3.950912e+08,9.451942e+07,1.017940e+08,18.089228
2,1.693272e+06,199999.968750,199999.96875,199999.96875,199999.96875,73877.859375,199999.968750,199999.96875,2742.082764,7.519018e+06,3.793589e+08,9.075571e+07,1.017940e+08,18.253036
3,1.693272e+06,199999.968750,199999.96875,199999.96875,199999.96875,73507.687500,199999.968750,199999.96875,3455.947998,1.194358e+07,3.603122e+08,8.619908e+07,8.619908e+07,18.382336
4,1.693272e+06,199999.968750,199999.96875,199999.96875,199999.96875,73673.351562,199999.968750,199999.96875,4107.472656,1.687133e+07,3.384560e+08,8.097033e+07,8.619908e+07,18.479101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16041,1.693337e+06,134414.203125,199999.96875,199999.96875,199999.96875,-6958.413086,134467.593750,199999.96875,-2.221680,4.935863e+00,8.398184e+00,1.454111e+00,1.444730e+00,-259.693542
16042,1.693337e+06,134332.843750,199999.96875,199999.96875,199999.96875,-6697.011719,134526.875000,199999.96875,-2.914265,8.492943e+00,8.330305e+00,1.437872e+00,1.444730e+00,-300.667664
16043,1.693337e+06,134519.375000,199999.96875,199999.96875,199999.96875,-6741.213867,134620.250000,199999.96875,-3.594482,1.292030e+01,8.358971e+00,1.444730e+00,1.444730e+00,-309.641937
16044,1.693337e+06,0.000000,0.00000,0.00000,0.00000,0.000000,0.000000,0.00000,-4.252551,1.808419e+01,8.505150e+00,1.479701e+00,1.444730e+00,-267.596771


In [750]:
eeg_df = eeg_df.rename(columns = {"Time": "LSL Time", "Ch08": "Theta Bandpass", "Ch09": "Power", "Ch10": "Moving Average", "Ch11": "Z-score", "Ch12": "Hold", "Ch13": "Trigger Channel"})
eeg_df

,LSL Time,Ch01,Ch02,Ch03,Ch04,Ch05,Ch06,Ch07,Theta Bandpass,Power,Moving Average,Z-score,Hold,Trigger Channel
0,1.693272e+06,199999.968750,199999.96875,199999.96875,199999.96875,73926.976562,199999.968750,199999.96875,1097.605103,1.204737e+06,4.072512e+08,9.742852e+07,1.017940e+08,17.890985
1,1.693272e+06,199999.968750,199999.96875,199999.96875,199999.96875,74181.585938,199999.968750,199999.96875,1958.274780,3.834840e+06,3.950912e+08,9.451942e+07,1.017940e+08,18.089228
2,1.693272e+06,199999.968750,199999.96875,199999.96875,199999.96875,73877.859375,199999.968750,199999.96875,2742.082764,7.519018e+06,3.793589e+08,9.075571e+07,1.017940e+08,18.253036
3,1.693272e+06,199999.968750,199999.96875,199999.96875,199999.96875,73507.687500,199999.968750,199999.96875,3455.947998,1.194358e+07,3.603122e+08,8.619908e+07,8.619908e+07,18.382336
4,1.693272e+06,199999.968750,199999.96875,199999.96875,199999.96875,73673.351562,199999.968750,199999.96875,4107.472656,1.687133e+07,3.384560e+08,8.097033e+07,8.619908e+07,18.479101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16041,1.693337e+06,134414.203125,199999.96875,199999.96875,199999.96875,-6958.413086,134467.593750,199999.96875,-2.221680,4.935863e+00,8.398184e+00,1.454111e+00,1.444730e+00,-259.693542
16042,1.693337e+06,134332.843750,199999.96875,199999.96875,199999.96875,-6697.011719,134526.875000,199999.96875,-2.914265,8.492943e+00,8.330305e+00,1.437872e+00,1.444730e+00,-300.667664
16043,1.693337e+06,134519.375000,199999.96875,199999.96875,199999.96875,-6741.213867,134620.250000,199999.96875,-3.594482,1.292030e+01,8.358971e+00,1.444730e+00,1.444730e+00,-309.641937
16044,1.693337e+06,0.000000,0.00000,0.00000,0.00000,0.000000,0.000000,0.00000,-4.252551,1.808419e+01,8.505150e+00,1.479701e+00,1.444730e+00,-267.596771


In [751]:
lifu_on = markers_df[markers_df["marker"]=="LIFU_ON"].copy()
lifu_on_timestamp = lifu_on["LSL_timestamp"]
lifu_on_timestamp = np.array(lifu_on_timestamp)
lifu_on_timestamp

array([1693298.1439491, 1693305.1699361, 1693312.1747948, 1693319.1889808,
       1693326.4774191, 1693335.987696 ])

In [752]:
calibration_complete = 1693298.110062

In [753]:
buffer = []
offline_z = []
medians = []
merged_df = eeg_df
mads = []
last_theta_val = None
last_median_val = None
last_mad_val = None

SONICATION_TIME = 5 #seconds i believe  
COOLDOWN_TIME = 7 #sonication time + cooldown time 
THETA_THRESHOLD_Z = 1.5    # z-score threshold
MU =  2.32
SIGMA =  4.18
MAD_THRESHOLD = 60       # for artifact rejection in baseline collection
INITIAL_CUTOFF = 100.0   # initial power threshold to exclude extreme artifacts
BUFFER_SIZE = 500
sonication_enabled = calibration_complete

# Ch05 = index 4
channel = "Hold"

for i in range(len(merged_df)):
    theta_val = merged_df[channel].iloc[i]   # MUST match online
    if last_theta_val is not None and theta_val == last_theta_val:
        offline_z.append(last_theta_val)
        medians.append(last_median_val)
        mads.append(last_theta_val)
        continue
    # Warm-up
    if len(buffer) <= 200:
        if theta_val < INITIAL_CUTOFF:
            buffer.append(theta_val)
        offline_z.append(np.nan)
        medians.append(np.nan)
        mads.append(np.nan)
        continue

    # Rolling buffer
    if len(buffer) > BUFFER_SIZE:
        buffer.pop(0)

    arr = np.array(buffer)
    median = np.median(arr)
    mad = np.median(np.abs(arr - median)) + 1e-6
    

    # Artifact rejection
    z_art = abs(theta_val - median) / mad
    if z_art > MAD_THRESHOLD:
        offline_z.append(np.nan)
        medians.append(np.nan)
        mads.append(np.nan)
        continue

    # Clean sample
    buffer.append(theta_val)
    last_theta_val = theta_val
    last_median_val = median
    last_mad_val = mad

    # Z-score
    offline_z.append(theta_val)
    medians.append(median)
    mads.append(mad)

merged_df["offline z-score"] = offline_z
merged_df["median"] = medians
merged_df['mad'] = mads

In [754]:
LIFU = np.zeros(len(merged_df))
last_trigger_time = -999

for i in range(len(merged_df)):
    theta_z = merged_df["offline z-score"].iloc[i]
    now = merged_df["LSL Time"].iloc[i]

    if now> sonication_enabled and theta_z > THETA_THRESHOLD_Z and theta_z < MAD_THRESHOLD and (now - last_trigger_time > COOLDOWN_TIME):
        LIFU[i] = 1.0
        last_trigger_time = now

In [755]:
merged_df["LIFU"] = LIFU
merged_df

,LSL Time,Ch01,Ch02,Ch03,Ch04,Ch05,Ch06,Ch07,Theta Bandpass,Power,Moving Average,Z-score,Hold,Trigger Channel,offline z-score,median,mad,LIFU
0,1.693272e+06,199999.968750,199999.96875,199999.96875,199999.96875,73926.976562,199999.968750,199999.96875,1097.605103,1.204737e+06,4.072512e+08,9.742852e+07,1.017940e+08,17.890985,NaN,NaN,NaN,0.0
1,1.693272e+06,199999.968750,199999.96875,199999.96875,199999.96875,74181.585938,199999.968750,199999.96875,1958.274780,3.834840e+06,3.950912e+08,9.451942e+07,1.017940e+08,18.089228,NaN,NaN,NaN,0.0
2,1.693272e+06,199999.968750,199999.96875,199999.96875,199999.96875,73877.859375,199999.968750,199999.96875,2742.082764,7.519018e+06,3.793589e+08,9.075571e+07,1.017940e+08,18.253036,NaN,NaN,NaN,0.0
3,1.693272e+06,199999.968750,199999.96875,199999.96875,199999.96875,73507.687500,199999.968750,199999.96875,3455.947998,1.194358e+07,3.603122e+08,8.619908e+07,8.619908e+07,18.382336,NaN,NaN,NaN,0.0
4,1.693272e+06,199999.968750,199999.96875,199999.96875,199999.96875,73673.351562,199999.968750,199999.96875,4107.472656,1.687133e+07,3.384560e+08,8.097033e+07,8.619908e+07,18.479101,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16041,1.693337e+06,134414.203125,199999.96875,199999.96875,199999.96875,-6958.413086,134467.593750,199999.96875,-2.221680,4.935863e+00,8.398184e+00,1.454111e+00,1.444730e+00,-259.693542,1.444730,18.007375,1.444730,0.0
16042,1.693337e+06,134332.843750,199999.96875,199999.96875,199999.96875,-6697.011719,134526.875000,199999.96875,-2.914265,8.492943e+00,8.330305e+00,1.437872e+00,1.444730e+00,-300.667664,1.444730,18.007375,1.444730,0.0
16043,1.693337e+06,134519.375000,199999.96875,199999.96875,199999.96875,-6741.213867,134620.250000,199999.96875,-3.594482,1.292030e+01,8.358971e+00,1.444730e+00,1.444730e+00,-309.641937,1.444730,18.007375,1.444730,0.0
16044,1.693337e+06,0.000000,0.00000,0.00000,0.00000,0.000000,0.000000,0.00000,-4.252551,1.808419e+01,8.505150e+00,1.479701e+00,1.444730e+00,-267.596771,1.444730,18.007375,1.444730,0.0


In [756]:
mask_lifu = merged_df["LIFU"] == 1.0
lifu_on_df = merged_df[mask_lifu]
lifu_on_df["LSL Time"] = lifu_on_df["LSL Time"]
lifu_on_cal = lifu_on_df[lifu_on_df["LSL Time"] > calibration_complete]
lifu_on_cal

C:\Users\jshin\AppData\Local\Temp\ipykernel_23040\4113107194.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lifu_on_df["LSL Time"] = lifu_on_df["LSL Time"]


,LSL Time,Ch01,Ch02,Ch03,Ch04,Ch05,Ch06,Ch07,Theta Bandpass,Power,Moving Average,Z-score,Hold,Trigger Channel,offline z-score,median,mad,LIFU
6594,1.693298e+06,63075.457031,199999.96875,199999.96875,199999.96875,277.256989,63048.605469,199999.96875,5.287420,27.956808,16.200684,3.320737,3.218442,-0.054152,3.218442,4.422082,3.218442,1.0
8343,1.693305e+06,51111.937500,199999.96875,199999.96875,199999.96875,327.420258,51062.156250,199999.96875,3.522665,12.409164,9.033171,1.606022,1.606022,-16.666235,1.606022,2.862997,3.055642,1.0
10092,1.693312e+06,46625.144531,199999.96875,199999.96875,199999.96875,342.845947,46558.957031,199999.96875,-6.683650,44.671165,56.406914,12.939453,13.021322,-16.405624,13.021322,4.364031,4.146283,1.0
11841,1.693319e+06,45618.207031,199999.96875,199999.96875,199999.96875,350.761414,45567.425781,199999.96875,11.215375,125.784645,30.584967,6.761954,7.891293,-15.626019,7.891293,6.818312,7.891293,1.0
13590,1.693326e+06,42597.511719,199999.96875,199999.96875,199999.96875,353.813171,42575.148438,199999.96875,5.493381,30.177227,217.730515,51.533619,48.589977,-15.657715,48.589977,10.369282,48.589977,1.0
15795,1.693336e+06,133375.171875,199999.96875,199999.96875,199999.96875,-8294.106445,133208.968750,199999.96875,-0.013355,0.000178,800.649231,190.987869,50.288414,-0.193651,50.288414,17.620301,13.709424,1.0


In [757]:
offline_ts = np.array(lifu_on_cal['LSL Time'])
offline_ts

array([1693298.1104972, 1693305.1275291, 1693312.1344147, 1693319.1383214,
       1693326.1393499, 1693335.9804633])

In [758]:
lifu_on_timestamp #- offline_ts

array([1693298.1439491, 1693305.1699361, 1693312.1747948, 1693319.1889808,
       1693326.4774191, 1693335.987696 ])

In [759]:
windows = []
for idx, ts in enumerate(offline_ts):
    window = eeg_df[abs(eeg_df['LSL Time'] - ts) < 0.1]
    windows.append(window)
#windows = np.array(windows)
windows[4]

,LSL Time,Ch01,Ch02,Ch03,Ch04,Ch05,Ch06,Ch07,Theta Bandpass,Power,Moving Average,Z-score,Hold,Trigger Channel,offline z-score,median,mad,LIFU
13566,1.693326e+06,43158.054688,199999.96875,199999.96875,199999.96875,354.123138,43120.242188,199999.96875,-11.012564,121.276550,120.054237,28.166086,25.856567,-7.488023,25.856567,10.326056,25.856567,0.0
13567,1.693326e+06,42968.300781,199999.96875,199999.96875,199999.96875,345.301666,42917.207031,199999.96875,-8.344167,69.625122,121.043091,28.402655,25.856567,-7.787417,25.856567,10.326056,25.856567,0.0
13568,1.693326e+06,42250.804688,199999.96875,199999.96875,199999.96875,347.733551,42214.875000,199999.96875,-5.441944,29.614756,121.252357,28.452719,25.856567,-7.988996,25.856567,10.326056,25.856567,0.0
13569,1.693326e+06,42339.855469,199999.96875,199999.96875,199999.96875,355.076813,42320.562500,199999.96875,-2.365880,5.597391,121.023361,28.397934,25.856567,-8.197157,25.856567,10.326056,25.856567,0.0
13570,1.693326e+06,43081.480469,199999.96875,199999.96875,199999.96875,352.883392,43046.769531,199999.96875,0.818838,0.670495,120.756447,28.334076,25.856567,-8.486203,25.856567,10.326056,25.856567,0.0
13571,1.693326e+06,43104.105469,199999.96875,199999.96875,199999.96875,345.325531,43043.925781,199999.96875,4.043288,16.348181,120.876205,28.362728,29.077616,-8.871292,29.077616,10.349335,7.043412,0.0
13572,1.693326e+06,42377.117188,199999.96875,199999.96875,199999.96875,347.208984,42338.898438,199999.96875,7.236412,52.365654,121.793091,28.582077,29.077616,-9.342641,29.077616,10.349335,29.077616,0.0
13573,1.693326e+06,42263.273438,199999.96875,199999.96875,199999.96875,353.908600,42246.867188,199999.96875,10.326701,106.640747,123.864426,29.077616,29.077616,-9.895955,29.077616,10.349335,29.077616,0.0
13574,1.693326e+06,42989.062500,199999.96875,199999.96875,199999.96875,354.361572,42955.398438,199999.96875,13.243955,175.402313,127.358849,29.913601,29.077616,-10.520345,29.077616,10.349335,29.077616,0.0
13575,1.693326e+06,43210.582031,199999.96875,199999.96875,199999.96875,346.565277,43153.023438,199999.96875,15.921026,253.479080,132.427490,31.126196,29.077616,-11.177661,29.077616,10.349335,29.077616,0.0


In [760]:
mask_lifu = merged_df["LIFU"] == 1.0
lifu_on_df = merged_df[mask_lifu]
lifu_on_cal = lifu_on_df[lifu_on_df["LSL Time"] > psychopy_started]
lifu_on_cal

,LSL Time,Ch01,Ch02,Ch03,Ch04,Ch05,Ch06,Ch07,Theta Bandpass,Power,Moving Average,Z-score,Hold,Trigger Channel,offline z-score,median,mad,LIFU
6594,1.693298e+06,63075.457031,199999.96875,199999.96875,199999.96875,277.256989,63048.605469,199999.96875,5.287420,27.956808,16.200684,3.320737,3.218442,-0.054152,3.218442,4.422082,3.218442,1.0
8343,1.693305e+06,51111.937500,199999.96875,199999.96875,199999.96875,327.420258,51062.156250,199999.96875,3.522665,12.409164,9.033171,1.606022,1.606022,-16.666235,1.606022,2.862997,3.055642,1.0
10092,1.693312e+06,46625.144531,199999.96875,199999.96875,199999.96875,342.845947,46558.957031,199999.96875,-6.683650,44.671165,56.406914,12.939453,13.021322,-16.405624,13.021322,4.364031,4.146283,1.0
11841,1.693319e+06,45618.207031,199999.96875,199999.96875,199999.96875,350.761414,45567.425781,199999.96875,11.215375,125.784645,30.584967,6.761954,7.891293,-15.626019,7.891293,6.818312,7.891293,1.0
13590,1.693326e+06,42597.511719,199999.96875,199999.96875,199999.96875,353.813171,42575.148438,199999.96875,5.493381,30.177227,217.730515,51.533619,48.589977,-15.657715,48.589977,10.369282,48.589977,1.0
15795,1.693336e+06,133375.171875,199999.96875,199999.96875,199999.96875,-8294.106445,133208.968750,199999.96875,-0.013355,0.000178,800.649231,190.987869,50.288414,-0.193651,50.288414,17.620301,13.709424,1.0


In [761]:
lifu_on_time = lifu_on_cal["LSL Time"]
lifu_on_time = np.array(lifu_on_time)
offline_lifu= lifu_on_time

In [762]:
offline_lifu # because the begin calibration didn't start yet that's why it doesn't

array([1693298.1104972, 1693305.1275291, 1693312.1344147, 1693319.1383214,
       1693326.1393499, 1693335.9804633])

In [763]:
target_ts

array([1002279.2847846, 1002505.9063606])

In [764]:
calibration_complete

1693298.110062

In [766]:
offline_lifu - lifu_on_timestamp

array([-0.0334519, -0.042407 , -0.0403801, -0.0506594, -0.3380692,
       -0.0072327])