In [369]:
import pandas as pd
import numpy as np
import os
import matplotlib as plt

In [522]:
scope = pd.read_csv("thetaEEG_gpype_2back_-1580742246_20260701_172435.csv")
scope

,Time,Ch01,Ch02,Ch03,Ch04,Ch05,Ch06,Ch07,Ch08
0,0.000,22533.943359,0.000287,8.214094e-08,1.642819e-09,-0.555024,4.987690,1.754461,0
1,0.004,22514.369141,0.004244,1.800972e-05,3.618373e-07,-0.555024,2226.845215,12.315079,0
2,0.008,22576.333984,0.030995,9.607024e-04,1.957589e-05,-0.555019,5733.327148,41.412243,0
3,0.012,22253.203125,0.149970,2.249094e-02,4.693947e-04,-0.554912,98214.023438,91.097473,0
4,0.016,21931.509766,0.544582,2.965694e-01,6.400784e-03,-0.553493,159863.750000,150.382172,0
...,...,...,...,...,...,...,...,...,...
35097,140.388,47554.261719,-13.287036,1.765453e+02,1.189455e+02,27.900829,25.320999,0.221822,0
35098,140.392,49825.363281,-14.501170,2.102839e+02,1.207226e+02,28.325989,28.801815,0.265673,0
35099,140.396,48792.718750,-15.476265,2.395148e+02,1.227116e+02,28.801815,28.801815,0.231822,0
35100,140.400,46401.457031,-16.009197,2.562944e+02,1.246938e+02,29.276037,28.801815,0.122959,0


In [501]:
scope = scope.rename(columns = {" Ch01": "Raw", " Ch02": "Theta Bandpass", " Ch03": "Power", " Ch04": "Moving Average", " Ch05": "Z-score", " Ch06": "Hold", " Ch07": "Trigger Channel", " Ch08": "Markers"})
scope

,Time,Raw,Theta Bandpass,Power,Moving Average,Z-score,Hold,Trigger Channel,Markers
0,0.000,22533.943359,0.000287,8.214094e-08,1.642819e-09,-0.555024,4.987690,1.754461,0
1,0.004,22514.369141,0.004244,1.800972e-05,3.618373e-07,-0.555024,2226.845215,12.315079,0
2,0.008,22576.333984,0.030995,9.607024e-04,1.957589e-05,-0.555019,5733.327148,41.412243,0
3,0.012,22253.203125,0.149970,2.249094e-02,4.693947e-04,-0.554912,98214.023438,91.097473,0
4,0.016,21931.509766,0.544582,2.965694e-01,6.400784e-03,-0.553493,159863.750000,150.382172,0
...,...,...,...,...,...,...,...,...,...
35097,140.388,47554.261719,-13.287036,1.765453e+02,1.189455e+02,27.900829,25.320999,0.221822,0
35098,140.392,49825.363281,-14.501170,2.102839e+02,1.207226e+02,28.325989,28.801815,0.265673,0
35099,140.396,48792.718750,-15.476265,2.395148e+02,1.227116e+02,28.801815,28.801815,0.231822,0
35100,140.400,46401.457031,-16.009197,2.562944e+02,1.246938e+02,29.276037,28.801815,0.122959,0


In [502]:
arrow = scope[scope['Markers'] == 38]
filtered = []
last_time = -np.inf

for _, row in arrow.iterrows():
    t = row['Time']
    if t - last_time >= 5.0:   # keep only if greater than 5 seconds apart
        filtered.append(row)
        last_time = t

filtered_arrow = pd.DataFrame(filtered)

# Step 3: extract channel 8 values
channel_8_eeg = np.array(filtered_arrow['Trigger Channel'])

lifu_on_ts = np.array(filtered_arrow['Time'])
lifu_on_ts

array([112.884, 124.58 ])

In [505]:
spaces = scope[scope['Markers']== 32]
psychopy_started = 49#  spaces.iloc[0]['Time']
psychopy_started

49

In [506]:
arrow

,Time,Raw,Theta Bandpass,Power,Moving Average,Z-score,Hold,Trigger Channel,Markers
28221,112.884,46117.929688,5.996557,35.958698,19.302795,4.062870,4.012880,435.825378,38
28222,112.888,48766.144531,6.046957,36.565685,19.490841,4.107857,4.012880,532.471069,38
28223,112.892,46802.074219,6.019568,36.235199,19.727596,4.164496,4.012880,469.139893,38
28224,112.896,44282.437500,5.914893,34.985954,20.005331,4.230941,4.012880,261.352295,38
28225,112.900,45604.656250,5.734450,32.883923,20.314358,4.304871,4.012880,7.822307,38
28226,112.904,48694.355469,5.480804,30.039215,20.643173,4.383535,4.012880,-174.633057,38
28227,112.908,47276.457031,5.157580,26.600637,20.978647,4.463791,4.012880,-237.006912,38
28228,112.912,44419.605469,4.769442,22.747580,21.306301,4.542178,4.012880,-212.188187,38
31145,124.580,45357.273438,1.798097,3.233153,7.395624,1.214264,1.179725,-0.232312,38
31146,124.584,47552.636719,1.431231,2.048423,7.436536,1.224052,1.179725,-0.314902,38


In [507]:
theta_val

-0.5550238490104675

In [508]:
merged_df = scope

In [509]:
buffer = []
offline_z = []
medians = []
mads = []
last_theta_val = None
last_median_val = None
last_mad_val = None

SONICATION_TIME = 5 #seconds i believe  
COOLDOWN_TIME = 15 #sonication time + cooldown time 
THETA_THRESHOLD_Z = 1.5    # z-score threshold
MU =  2.32
SIGMA =  4.18
MAD_THRESHOLD = 6       # for artifact rejection in baseline collection
INITIAL_CUTOFF = 100.0   # initial power threshold to exclude extreme artifacts
BUFFER_SIZE = 500
sonication_enabled = psychopy_started

# Ch05 = index 4
channel = "Hold"

for i in range(len(merged_df)):
    theta_val = merged_df[channel].iloc[i]   # MUST match online
    if last_theta_val is not None and theta_val == last_theta_val:
        offline_z.append(last_theta_val)
        medians.append(last_median_val)
        mads.append(last_theta_val)
        continue
    # Warm-up
    if len(buffer) <= 200:
        if theta_val < INITIAL_CUTOFF:
            buffer.append(theta_val)
        offline_z.append(np.nan)
        medians.append(np.nan)
        mads.append(np.nan)
        continue

    # Rolling buffer
    if len(buffer) > BUFFER_SIZE:
        buffer.pop(0)

    arr = np.array(buffer)
    median = np.median(arr)
    mad = np.median(np.abs(arr - median)) + 1e-6
    

    # Artifact rejection
    z_art = abs(theta_val - median) / mad
    if z_art > MAD_THRESHOLD:
        offline_z.append(np.nan)
        medians.append(np.nan)
        mads.append(np.nan)
        continue

    # Clean sample
    buffer.append(theta_val)
    last_theta_val = theta_val
    last_median_val = median
    last_mad_val = mad

    # Z-score
    offline_z.append(theta_val)
    medians.append(median)
    mads.append(mad)

merged_df["offline z-score"] = offline_z
merged_df["median"] = medians
merged_df['mad'] = mads

In [510]:
LIFU = np.zeros(len(merged_df))
last_trigger_time = -999

for i in range(len(merged_df)):
    theta_z = merged_df["offline z-score"].iloc[i]
    now = merged_df["Time"].iloc[i]

    if now> sonication_enabled and theta_z > THETA_THRESHOLD_Z and theta_z < MAD_THRESHOLD and (now - last_trigger_time > COOLDOWN_TIME):
   # if time.  and theta_val < MAD_THRESHOLD and theta_val > THETA_THRESHOLD_Z and (now - last_trigger_time) > COOLDOWN_TIME:
        LIFU[i] = 1.0
        last_trigger_time = now

In [511]:
sum(LIFU)

2.0

In [512]:
merged_df["LIFU"] = LIFU
merged_df

,Time,Raw,Theta Bandpass,Power,Moving Average,Z-score,Hold,Trigger Channel,Markers,offline z-score,median,mad,LIFU
0,0.000,22533.943359,0.000287,8.214094e-08,1.642819e-09,-0.555024,4.987690,1.754461,0,NaN,NaN,NaN,0.0
1,0.004,22514.369141,0.004244,1.800972e-05,3.618373e-07,-0.555024,2226.845215,12.315079,0,NaN,NaN,NaN,0.0
2,0.008,22576.333984,0.030995,9.607024e-04,1.957589e-05,-0.555019,5733.327148,41.412243,0,NaN,NaN,NaN,0.0
3,0.012,22253.203125,0.149970,2.249094e-02,4.693947e-04,-0.554912,98214.023438,91.097473,0,NaN,NaN,NaN,0.0
4,0.016,21931.509766,0.544582,2.965694e-01,6.400784e-03,-0.553493,159863.750000,150.382172,0,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
35097,140.388,47554.261719,-13.287036,1.765453e+02,1.189455e+02,27.900829,25.320999,0.221822,0,NaN,NaN,NaN,0.0
35098,140.392,49825.363281,-14.501170,2.102839e+02,1.207226e+02,28.325989,28.801815,0.265673,0,NaN,NaN,NaN,0.0
35099,140.396,48792.718750,-15.476265,2.395148e+02,1.227116e+02,28.801815,28.801815,0.231822,0,NaN,NaN,NaN,0.0
35100,140.400,46401.457031,-16.009197,2.562944e+02,1.246938e+02,29.276037,28.801815,0.122959,0,NaN,NaN,NaN,0.0


In [513]:
mask_lifu = merged_df["LIFU"] == 1.0
lifu_on_df = merged_df[mask_lifu]
lifu_on_cal = lifu_on_df[lifu_on_df["Time"] > psychopy_started]
lifu_on_cal

,Time,Raw,Theta Bandpass,Power,Moving Average,Z-score,Hold,Trigger Channel,Markers,offline z-score,median,mad,LIFU
27369,109.476,45669.960938,4.517487,20.407684,8.740285,1.535953,1.535953,-0.317358,0,1.535953,-0.109108,0.290858,1.0
31120,124.480,45331.605469,-0.388396,0.150852,10.095790,1.860237,1.876970,-0.102606,0,1.876970,0.322368,1.876970,1.0


In [514]:
lifu_on_ts

array([112.884, 124.58 ])

In [515]:
lifu_on_time = lifu_on_cal["Time"]
lifu_on_time = np.array(lifu_on_time)
offline_lifu= lifu_on_time

In [516]:
offline_lifu # because the begin calibration didn't start yet that's why it doesn't

array([109.476, 124.48 ])

In [519]:
target_ts

array([1002279.2847846, 1002505.9063606])

In [216]:
calibration_complete

1002278.9429925

In [520]:
offline_lifu - target_ts

array([-1002169.8087846, -1002381.4263606])

In [521]:
# windowing ONLINE
windows = []
for idx, ts in enumerate(lifu_on_ts):
    window = scope[abs(scope['Time'] - 124.52) < 0.1]
    windows.append(window)
windows = pd.DataFrame(windows[1])
windows

,Time,Raw,Theta Bandpass,Power,Moving Average,Z-score,Hold,Trigger Channel,Markers,offline z-score,median,mad,LIFU
31105,124.420,49605.925781,-3.863769,14.928711,12.630789,2.466696,2.282070,0.137406,0,2.282070,0.312614,2.282070,0.0
31106,124.424,48318.867188,-3.984620,15.877195,12.689748,2.480801,2.282070,0.270236,0,2.282070,0.312614,2.282070,0.0
31107,124.428,45422.148438,-4.037325,16.299997,12.691867,2.481308,2.282070,0.338433,0,2.282070,0.312614,2.282070,0.0
31108,124.432,46059.679688,-4.023608,16.189423,12.630689,2.466672,2.282070,0.323459,0,2.282070,0.312614,2.282070,0.0
31109,124.436,49260.429688,-3.946248,15.572876,12.505013,2.436606,2.436606,0.257962,0,2.436606,0.318821,0.472427,0.0
31110,124.440,48705.367188,-3.808961,14.508186,12.319052,2.392118,2.436606,0.188696,0,2.436606,0.318821,2.436606,0.0
31111,124.444,45771.386719,-3.616297,13.077606,12.082052,2.335419,2.436606,0.122894,0,2.436606,0.318821,2.436606,0.0
31112,124.448,45776.773438,-3.373521,11.380644,11.807422,2.269718,2.436606,0.030519,0,2.436606,0.318821,2.436606,0.0
31113,124.452,48748.898438,-3.086496,9.526456,11.511442,2.198909,2.436606,-0.094270,0,2.436606,0.318821,2.436606,0.0
31114,124.456,49063.468750,-2.761556,7.626193,11.211734,2.127209,2.436606,-0.200634,0,2.436606,0.318821,2.436606,0.0


In [219]:
# channel_8 = eeg_df.nlargest(15, "Trigger Channel")
channel_8_sorted = channel_8.sort_values("LSL Time", ascending=False) # descending
MIN_SPACING = 10.0  # seconds
kept_rows = []
last_time = 0

for _, row in channel_8_sorted.iterrows():
    t = row["LSL Time"]
    if np.abs(t - last_time) >= MIN_SPACING:
        kept_rows.append(row)
        last_time = t
    if len(kept_rows) == 15:
        break
ttl_signal = pd.DataFrame(kept_rows)
ttl_signal_time = np.array(ttl_signal['LSL Time'])
ttl_signal_time = np.sort(ttl_signal_time)
target_ts- ttl_signal_time

array([-1.0603386, -5.2712901])

In [ ]:
#windowing raw eeg
raw = pd.read_csv("offline_2back_active.csv")
#raw = raw_with08.drop(' Ch08', axis = 1)
pre = 2
post = 10
raw_windows = []
target_ts_onset = np.array(lifu_on['Time'])


for idx, event in enumerate(target_ts_onset): 
    mask = (raw['Time'] >= (event - pre)) & (raw['Time'] <= (event + post))
    window_df = raw.loc[mask].copy()
    window_df["t_rel"] = window_df["Time"] - event 
    window_df["idx"] = idx
    raw_windows.append(window_df)
raw_windows[0]

In [227]:
#windowing scope eeg
pre = 0.1
post = 0.1
theta_windows = []


for idx, event in enumerate(target_ts): 
    mask = (eeg_df['LSL Time'] >= (event - pre)) & (eeg_df['LSL Time'] <= (event + post))
    window_df = eeg_df.loc[mask].copy()
    window_df["t_rel"] = window_df["LSL Time"] - event 
    window_df["idx"] = idx
    theta_windows.append(window_df)
theta_windows[0].head(5)

,LSL Time,Raw,Theta Bandpass,Power,Moving Average,Z-score,Hold,Trigger Channel,offline z-score,median,mad,LIFU,t_rel,idx
32729,1.002279e+06,36951.019531,0.426223,0.181666,17.629465,3.662551,3.792289,-0.013578,NaN,NaN,NaN,0.0,-0.096979,0
32730,1.002279e+06,37469.867188,-0.181108,0.032800,17.614086,3.658872,3.792289,0.068717,NaN,NaN,NaN,0.0,-0.090535,0
32731,1.002279e+06,37547.949219,-0.738689,0.545661,17.623901,3.661220,3.792289,0.144538,NaN,NaN,NaN,0.0,-0.089937,0
32732,1.002279e+06,37027.929688,-1.233583,1.521728,17.650528,3.667590,3.674807,0.173848,NaN,NaN,NaN,0.0,-0.086437,0
32733,1.002279e+06,36884.117188,-1.655106,2.739376,17.680695,3.674807,3.674807,0.108562,NaN,NaN,NaN,0.0,-0.083526,0


In [ ]:
#base_dir_raw = r"C:\Users\jshin\OW_closedloopLIFU\eeg_windows\raw"
base_dir_scope=r"C:\Users\jshin\OW_closedloopLIFU\eeg_windows\scope"
# MAKE SURE TO PUT IN NAME
new_folder_name = "active"
#new_folder_path_raw = os.path.join(base_dir_raw, new_folder_name)
new_folder_path_scope = os.path.join(base_dir_scope, new_folder_name)
#os.makedirs(new_folder_path_raw, exist_ok=False) # check
os.makedirs(new_folder_path_scope, exist_ok=False) # check

for idx, event in enumerate(target_ts_onset):
    # Build a unique filename for each event
    #output_path_raw = os.path.join(new_folder_path_raw, f"{idx}_{event}_eeg_raw.csv")
    output_path_scope = os.path.join(new_folder_path_scope, f"{idx}_{event}_eeg_scope.csv")
    try:
        #raw_windows[idx].to_csv(output_path_raw, index=False, encoding="utf-8")
        theta_windows[idx].to_csv(output_path_scope, index=False, encoding="utf-8")
        #print(f"Saved successfully to: {output_path_raw}")
        print(f"Saved successfully to: {output_path_scope}")
    except (OSError, IOError) as e:
        print(f"Error saving CSV file: {e}")
