In [1]:
import pyxdf
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [4]:
data, header = pyxdf.load_xdf("../lab_recorder_data/sub-scott_sham1_ses-scott_sham1_task-Default_run-001_eeg.xdf")
data

[{'info': defaultdict(list,
              {'name': ['PsychoPyMarkers'],
               'type': ['Markers'],
               'channel_count': ['1'],
               'channel_format': ['string'],
               'source_id': ['-4379379051682882619'],
               'nominal_srate': ['0.000000000000000'],
               'version': ['1.100000000000000'],
               'created_at': ['2126654.882835100'],
               'uid': ['443a876e-6c81-4320-b1c4-53fc740472e4'],
               'session_id': ['default'],
               'hostname': ['JanetsPC'],
               'v4address': [None],
               'v4data_port': ['16575'],
               'v4service_port': ['16580'],
               'v6address': [None],
               'v6data_port': ['16575'],
               'v6service_port': ['16580'],
               'desc': [None],
               'stream_id': 1,
               'effective_srate': 0,
               'segments': [(0, 99)],
               'clock_segments': [(0, 99)]}),
  'footer': {'info': defau

In [ ]:
data

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,42082.648438,20786.525391,10384.942383,13134.862305,32778.500000,50584.773438,56421.093750,0.533888,0.285036,1.941486,-0.517957,-0.374694,-0.415687
1,41866.519531,20716.193359,10511.184570,13218.117188,32831.218750,50300.460938,56478.835938,0.247424,0.061219,1.795327,-0.540102,-0.374694,-0.546212
2,42414.187500,21033.291016,10112.310547,12833.953125,32569.150391,50980.550781,56422.710938,-0.057246,0.003277,1.662127,-0.560284,-0.560284,-0.594477
3,42800.429688,21225.953125,9883.427734,12634.445312,32442.240234,51498.230469,56354.480469,-0.372842,0.139011,1.548129,-0.577556,-0.560284,-0.494768
4,42137.511719,20810.130859,10316.659180,13035.036133,32732.417969,50667.148438,56380.113281,-0.691347,0.477961,1.458847,-0.591084,-0.560284,-0.295945
...,...,...,...,...,...,...,...,...,...,...,...,...,...
57541,41172.554688,20478.896484,9971.596680,13088.465820,32628.464844,39031.148438,56847.699219,-21.081528,444.430817,114.382103,16.518503,10.832265,-0.062478
57542,41571.050781,20707.964844,9636.474609,12801.934570,32424.740234,39632.136719,56720.281250,-21.398880,457.912048,123.532997,17.904999,17.904999,-0.095029
57543,40984.707031,20331.552734,10063.195312,13272.833984,32685.687500,38858.843750,56758.242188,-21.262808,452.107025,132.488159,19.261841,17.904999,-0.130580
57544,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-20.673401,427.389496,140.783890,20.518774,17.904999,-1.747336


In [16]:
stream = data[3]
df= []
df = pd.DataFrame(stream['time_series'])
df = df.rename(columns={i: f"Ch{i}" for i in range(df.shape[1])})

# Add timestamp column
df['Timestamp'] = stream['time_stamps']

# Move Timestamp to be the first column after the index
cols = ['Timestamp'] + [col for col in df.columns if col != 'Timestamp']
df = df[cols]
df

,Timestamp,Ch0,Ch1,Ch2,Ch3,Ch4,Ch5,Ch6,Ch7,Ch8,Ch9,Ch10,Ch11,Ch12
0,2.126672e+06,42082.648438,20786.525391,10384.942383,13134.862305,32778.500000,50584.773438,56421.093750,0.533888,0.285036,1.941486,-0.517957,-0.374694,-0.415687
1,2.126672e+06,41866.519531,20716.193359,10511.184570,13218.117188,32831.218750,50300.460938,56478.835938,0.247424,0.061219,1.795327,-0.540102,-0.374694,-0.546212
2,2.126672e+06,42414.187500,21033.291016,10112.310547,12833.953125,32569.150391,50980.550781,56422.710938,-0.057246,0.003277,1.662127,-0.560284,-0.560284,-0.594477
3,2.126672e+06,42800.429688,21225.953125,9883.427734,12634.445312,32442.240234,51498.230469,56354.480469,-0.372842,0.139011,1.548129,-0.577556,-0.560284,-0.494768
4,2.126672e+06,42137.511719,20810.130859,10316.659180,13035.036133,32732.417969,50667.148438,56380.113281,-0.691347,0.477961,1.458847,-0.591084,-0.560284,-0.295945
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57541,2.126902e+06,41172.554688,20478.896484,9971.596680,13088.465820,32628.464844,39031.148438,56847.699219,-21.081528,444.430817,114.382103,16.518503,10.832265,-0.062478
57542,2.126902e+06,41571.050781,20707.964844,9636.474609,12801.934570,32424.740234,39632.136719,56720.281250,-21.398880,457.912048,123.532997,17.904999,17.904999,-0.095029
57543,2.126902e+06,40984.707031,20331.552734,10063.195312,13272.833984,32685.687500,38858.843750,56758.242188,-21.262808,452.107025,132.488159,19.261841,17.904999,-0.130580
57544,2.126902e+06,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-20.673401,427.389496,140.783890,20.518774,17.904999,-1.747336


In [23]:
print("Streams found:", [s['info']['name'][0] for s in data])

Streams found: ['PsychoPyMarkers', 'EEG_LIFU_events', 'PsychoPy_numeric', 'EEG_gpype']


In [41]:
EEG_LIFU_events = data[1]

# Create DataFrame from time_series
markers = pd.DataFrame(EEG_LIFU_events['time_series'])

# Rename the first column to 'markers'
markers.rename(columns={0: 'markers'}, inplace=True)

# Add timestamp column
markers['Timestamp'] = EEG_LIFU_events['time_stamps']

# Move Timestamp to be the first column after the index
cols = ['Timestamp'] + [col for col in markers.columns if col != 'Timestamp']
markers = markers[cols]
markers

,Timestamp,markers
0,2.126684e+06,START_EXPERIMENT_RECEIVED
1,2.126685e+06,LIFU_ON
2,2.126690e+06,LIFU_OFF
3,2.126702e+06,LIFU_ON
4,2.126707e+06,LIFU_OFF
5,2.126722e+06,LIFU_ON
6,2.126727e+06,LIFU_OFF
7,2.126737e+06,LIFU_ON
8,2.126742e+06,LIFU_OFF
9,2.126752e+06,LIFU_ON


In [37]:
lifu_on = markers[markers['markers'] == 'LIFU_ON']
lifu_on = np.array(lifu_on['Timestamp'])
lifu_on

array([2126684.8026258 , 2126701.73062089, 2126721.61227271,
       2126736.73185857, 2126752.12881684, 2126768.73627831,
       2126786.04525023, 2126802.6570825 , 2126817.73118836,
       2126833.77098548, 2126850.41133355])

In [53]:
start = markers[markers['markers'] == 'START_EXPERIMENT_RECEIVED']
start = start.iloc[0]['Timestamp']


In [61]:
buffer = []
offline_z = []
medians = []
merged_df = df
mads = []
last_theta_val = None
last_median_val = None
last_mad_val = None

SONICATION_TIME = 5 #seconds i believe  
COOLDOWN_TIME = 15 #sonication time + cooldown time 
THETA_THRESHOLD_Z = 1.5    # z-score threshold
MU =  5.36
SIGMA =  6.60
MAD_THRESHOLD = 6       # for artifact rejection in baseline collection
INITIAL_CUTOFF = 50.0   # initial power threshold to exclude extreme artifacts
BUFFER_SIZE = 500
sonication_enabled = start

# Ch05 = index 4
channel = "Ch11"

for i in range(len(merged_df)):
    theta_val = merged_df[channel].iloc[i]   # MUST match online
    if last_theta_val is not None and theta_val == last_theta_val:
        offline_z.append(last_theta_val)
        medians.append(last_median_val)
        mads.append(last_theta_val)
        continue
    # Warm-up
    if len(buffer) <= 200:
        if theta_val < INITIAL_CUTOFF:
            buffer.append(theta_val)
        offline_z.append(np.nan)
        medians.append(np.nan)
        mads.append(np.nan)
        continue

    # Rolling buffer
    if len(buffer) > BUFFER_SIZE:
        buffer.pop(0)

    arr = np.array(buffer)
    median = np.median(arr)
    mad = np.median(np.abs(arr - median)) + 1e-6
    

    # Artifact rejection
    z_art = abs(theta_val - median) / mad
    if z_art > MAD_THRESHOLD:
        offline_z.append(np.nan)
        medians.append(np.nan)
        mads.append(np.nan)
        continue

    # Clean sample
    buffer.append(theta_val)
    last_theta_val = theta_val
    last_median_val = median
    last_mad_val = mad

    # Z-score
    offline_z.append(theta_val)
    medians.append(median)
    mads.append(mad)

merged_df["offline z-score"] = offline_z
merged_df["median"] = medians
merged_df['mad'] = mads

In [62]:
LIFU = np.zeros(len(merged_df))
last_trigger_time = -999

for i in range(len(merged_df)):
    theta_z = merged_df["offline z-score"].iloc[i]
    now = merged_df["Timestamp"].iloc[i]

    if now> sonication_enabled and theta_z > THETA_THRESHOLD_Z and theta_z < MAD_THRESHOLD and (now - last_trigger_time > COOLDOWN_TIME):
        LIFU[i] = 1.0
        last_trigger_time = now

In [63]:
merged_df["LIFU"] = LIFU
merged_df

,Timestamp,Ch0,Ch1,Ch2,Ch3,Ch4,Ch5,Ch6,Ch7,Ch8,Ch9,Ch10,Ch11,Ch12,offline z-score,median,mad,LIFU
0,2.126672e+06,42082.648438,20786.525391,10384.942383,13134.862305,32778.500000,50584.773438,56421.093750,0.533888,0.285036,1.941486,-0.517957,-0.374694,-0.415687,NaN,NaN,NaN,0.0
1,2.126672e+06,41866.519531,20716.193359,10511.184570,13218.117188,32831.218750,50300.460938,56478.835938,0.247424,0.061219,1.795327,-0.540102,-0.374694,-0.546212,NaN,NaN,NaN,0.0
2,2.126672e+06,42414.187500,21033.291016,10112.310547,12833.953125,32569.150391,50980.550781,56422.710938,-0.057246,0.003277,1.662127,-0.560284,-0.560284,-0.594477,NaN,NaN,NaN,0.0
3,2.126672e+06,42800.429688,21225.953125,9883.427734,12634.445312,32442.240234,51498.230469,56354.480469,-0.372842,0.139011,1.548129,-0.577556,-0.560284,-0.494768,NaN,NaN,NaN,0.0
4,2.126672e+06,42137.511719,20810.130859,10316.659180,13035.036133,32732.417969,50667.148438,56380.113281,-0.691347,0.477961,1.458847,-0.591084,-0.560284,-0.295945,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57541,2.126902e+06,41172.554688,20478.896484,9971.596680,13088.465820,32628.464844,39031.148438,56847.699219,-21.081528,444.430817,114.382103,16.518503,10.832265,-0.062478,NaN,NaN,NaN,0.0
57542,2.126902e+06,41571.050781,20707.964844,9636.474609,12801.934570,32424.740234,39632.136719,56720.281250,-21.398880,457.912048,123.532997,17.904999,17.904999,-0.095029,NaN,NaN,NaN,0.0
57543,2.126902e+06,40984.707031,20331.552734,10063.195312,13272.833984,32685.687500,38858.843750,56758.242188,-21.262808,452.107025,132.488159,19.261841,17.904999,-0.130580,NaN,NaN,NaN,0.0
57544,2.126902e+06,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-20.673401,427.389496,140.783890,20.518774,17.904999,-1.747336,NaN,NaN,NaN,0.0


In [64]:
mask_lifu = merged_df["LIFU"] == 1.0
lifu_on_df = merged_df[mask_lifu]
lifu_on_df["Timestamp"] = lifu_on_df["Timestamp"]
lifu_on_cal = lifu_on_df[lifu_on_df["Timestamp"] > start]
lifu_on_cal

C:\Users\jshin\AppData\Local\Temp\ipykernel_6808\1311862906.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lifu_on_df["Timestamp"] = lifu_on_df["Timestamp"]


,Timestamp,Ch0,Ch1,Ch2,Ch3,Ch4,Ch5,Ch6,Ch7,Ch8,Ch9,Ch10,Ch11,Ch12,offline z-score,median,mad,LIFU
3222,2.126685e+06,41547.875000,20569.015625,10615.921875,10512.208984,32972.023438,50409.031250,56659.417969,-8.046468,64.745644,21.560394,2.454605,2.454605,0.120880,2.454605,-0.075113,0.484928,1.0
7452,2.126702e+06,41266.250000,20729.853516,10340.976562,8540.036133,32853.800781,50552.273438,56686.187500,4.051147,16.411789,17.236609,1.799486,1.799486,-0.281466,1.799486,-0.066250,0.402780,1.0
12422,2.126722e+06,40933.750000,20852.042969,10112.096680,8336.091797,32720.927734,50739.488281,56553.750000,-7.414465,54.974297,15.560725,1.545565,1.545565,-0.149320,1.545565,-0.196175,0.330812,1.0
16201,2.126737e+06,41324.238281,21406.984375,9601.640625,8603.073242,32355.621094,51570.824219,56470.085938,-7.637331,58.328827,16.793329,1.732323,1.924567,-0.126421,1.924567,-0.196385,0.371643,1.0
20052,2.126752e+06,41107.468750,21378.662109,9659.458008,6987.048340,32327.964844,51580.957031,56500.960938,3.429293,11.760054,16.931911,1.753320,1.753320,0.314565,1.753320,0.089161,0.448737,1.0
24202,2.126769e+06,41061.574219,21523.000000,9786.416992,4930.115723,32397.083984,51654.917969,56641.800781,8.081001,65.302589,21.252802,2.408000,2.408000,-0.378362,2.408000,-0.063966,0.489539,1.0
28532,2.126786e+06,40780.480469,21243.121094,9706.044922,4262.662598,32340.603516,51487.398438,56476.593750,0.922336,0.850705,15.841594,1.588120,1.588120,0.001822,1.588120,-0.177133,0.393123,1.0
32682,2.126803e+06,40831.144531,21407.990234,9592.200195,7854.628906,32230.740234,51574.949219,56472.355469,-4.561038,20.803066,17.437481,1.829921,1.829921,-0.258510,1.829921,0.056214,0.467671,1.0
36452,2.126818e+06,40407.761719,21028.568359,10124.349609,8011.460938,32648.947266,43536.886719,56695.937500,-5.631065,31.708899,26.841900,3.254833,3.254833,-0.007448,3.254833,0.148954,0.617534,1.0
40462,2.126834e+06,40700.988281,21211.531250,9937.906250,9149.528320,32540.656250,40049.625000,56547.675781,6.450368,41.607258,15.545135,1.543202,1.543202,-0.365366,1.543202,0.453352,0.842431,1.0


In [67]:
offline = np.array(lifu_on_cal['Timestamp'])
offline

array([2126684.80441875, 2126701.72515681, 2126721.60602398,
       2126736.72268335, 2126752.12735528, 2126768.72807938,
       2126786.04883488, 2126802.64955898, 2126817.73021677,
       2126833.77091644, 2126850.41164229, 2126866.65235068])

In [68]:
online = lifu_on
online

array([2126684.8026258 , 2126701.73062089, 2126721.61227271,
       2126736.73185857, 2126752.12881684, 2126768.73627831,
       2126786.04525023, 2126802.6570825 , 2126817.73118836,
       2126833.77098548, 2126850.41133355])

In [70]:
online - offline[:-1]

array([-1.79295568e-03,  5.46408119e-03,  6.24872744e-03,  9.17521678e-03,
        1.46156549e-03,  8.19893600e-03, -3.58464615e-03,  7.52352457e-03,
        9.71581321e-04,  6.90361485e-05, -3.08735296e-04])